import '../models/loan.dart';
import '../models/credit_profile.dart';
import 'package:intl/intl.dart';

class ContractBuilderService {
  /// Generates a human-readable, shareable loan agreement summary.
  /// Designed for offline sharing via WhatsApp or SMS.
  String generateContractSummary(Loan loan, CreditProfile profile) {
    final df = DateFormat('dd MMM yyyy');
    final currencyFormat = NumberFormat.currency(symbol: 'Ksh ', decimalDigits: 2);

    return '''
🇰🇪 KIPEPEO LOAN AGREEMENT 🇰🇪
-----------------------------
Borrower ID: ${profile.id.substring(0, 8)}...
Loan Reference: ${loan.id}

PROPOSED TERMS:
- Principal: ${currencyFormat.format(loan.principalAmount)}
- Interest Rate: ${(loan.interestRate * 100).toStringAsFixed(1)}%
- Total Repayable: ${currencyFormat.format(loan.totalToRepay)}

TIMELINE:
- Issued Date: ${df.format(loan.issuedDate)}
- Due Date: ${df.format(loan.dueDate)}

GOVERNANCE NOTICE:
This loan was generated by the Kipepeo Edge Engine. 
Decision based on local M-Pesa history.
Privacy Protected by ε-Differential Privacy.

*Please ensure timely repayment to maintain your Kipepeo Score.*
-----------------------------
Generated locally on-device.
''';
  }
}
